server:
  port: 8080
deploy:
  resultFile: /home/ubuntu/workspace/ydyl-deployment-suite/output/{{.L2Type}}-gen-meta.json
  opContractFile: /home/ubuntu/workspace/ydyl-deployment-suite/op-work/output/deploy-result-gen.json
  cdkContractFile: /home/ubuntu/workspace/ydyl-deployment-suite/cdk-work/output/deploy-result-gen.json
  pipelineStateFile: /home/ubuntu/workspace/ydyl-deployment-suite/output/{{.L2Type}}_pipe.state